version: "3"
services:
  backend: 
    container_name: product_be
    restart: always
    ports: 
     - 8080:8080
    networks:
      - app_network
  frontend: 
    container_name: product_fe
    restart: always
    ports: 
     - 3000:3000
    networks:
      - app_network
  data: 
    container_name: product_data
    restart: always
    ports: 
     - 8000:8000
    networks:
      - app_network
networks:
  app_network: 
    external: true

