version: "3.9"

services:
  fastapi_app:
    build:      
      context: ./data
      dockerfile: Dockerfile
    image: my_fastapi_app
    ports:
      - "8000:8000"
    container_name: my_fastapi_container
    
